// <auto-generated />
using GestaoInvestimentosInfrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestaoInvestimentosInfrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestaoInvestimentosCore.Entities.Ativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<int>("TipoAtivo")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.ToTable("Ativo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "ATV01",
                            Nome = "Nome Ativo 1",
                            TipoAtivo = 1
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "ATV02",
                            Nome = "Nome Ativo 2",
                            TipoAtivo = 2
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "ATV03",
                            Nome = "Nome Ativo 3",
                            TipoAtivo = 3
                        });
                });

            modelBuilder.Entity("GestaoInvestimentosCore.Entities.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Portfolio", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Descricao Portfolio 1",
                            Nome = "Nome Portfolio 1",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Descricao Portfolio 2",
                            Nome = "Nome Portfolio 2",
                            UsuarioId = 2
                        });
                });

            modelBuilder.Entity("GestaoInvestimentosCore.Entities.Transacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtivoId")
                        .HasColumnType("INT");

                    b.Property<string>("DataTransacao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("INT");

                    b.Property<string>("Preco")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Quantidade")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<int>("TipoTransacao")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.HasIndex("AtivoId");

                    b.HasIndex("PortfolioId");

                    b.ToTable("Transacao", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AtivoId = 1,
                            DataTransacao = "2024-06-08 11:49:52.6986499",
                            PortfolioId = 1,
                            Preco = "150",
                            Quantidade = "10",
                            TipoTransacao = 1
                        },
                        new
                        {
                            Id = 2,
                            AtivoId = 2,
                            DataTransacao = "2024-06-08 11:49:52.6986515",
                            PortfolioId = 1,
                            Preco = "300",
                            Quantidade = "20",
                            TipoTransacao = 2
                        },
                        new
                        {
                            Id = 3,
                            AtivoId = 1,
                            DataTransacao = "2024-06-08 11:49:52.6986517",
                            PortfolioId = 2,
                            Preco = "600",
                            Quantidade = "50",
                            TipoTransacao = 1
                        },
                        new
                        {
                            Id = 4,
                            AtivoId = 2,
                            DataTransacao = "2024-06-08 11:49:52.6986519",
                            PortfolioId = 2,
                            Preco = "900",
                            Quantidade = "90",
                            TipoTransacao = 2
                        });
                });

            modelBuilder.Entity("GestaoInvestimentosCore.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("Nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.ToTable("Usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "rm352321@fiap.com.br",
                            Nome = "Demetrios Pandelis Arghirachis",
                            Senha = "1q2w3e4r@#"
                        },
                        new
                        {
                            Id = 2,
                            Email = "usuario@teste.io",
                            Nome = "usuario teste",
                            Senha = "1q2w3e4r@#"
                        });
                });

            modelBuilder.Entity("GestaoInvestimentosCore.Entities.Portfolio", b =>
                {
                    b.HasOne("GestaoInvestimentosCore.Entities.Usuario", "Usuario")
                        .WithMany("Portfolios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestaoInvestimentosCore.Entities.Transacao", b =>
                {
                    b.HasOne("GestaoInvestimentosCore.Entities.Ativo", "Ativo")
                        .WithMany("Transacoes")
                        .HasForeignKey("AtivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoInvestimentosCore.Entities.Portfolio", "Portfolio")
                        .WithMany("Transacoes")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ativo");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("GestaoInvestimentosCore.Entities.Ativo", b =>
                {
                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("GestaoInvestimentosCore.Entities.Portfolio", b =>
                {
                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("GestaoInvestimentosCore.Entities.Usuario", b =>
                {
                    b.Navigation("Portfolios");
                });
#pragma warning restore 612, 618
        }
    }
}
